local:
  python: python --version
  helm: helm version --short
  kubectl: kubectl version --client=true --short
  docker: docker version --format json
  astro: astro version
  docker-compose: docker-compose --version
  os: uname -a
  aws: aws --version
  gcp: gcloud version --format=json
  az: az version
  verify:
    helm: helm ls -aA -o json
    astro_config: cat config.yaml


airflow_report: &airflow_report
  - /bin/sh
  - -c
  - curl -ssl https://raw.githubusercontent.com/fritz-astronomer/telescope/json2/airflow_debug_report.py | PYTHONWARNINGS=ignore AIRFLOW_REPORT_OUTPUT=- python

docker:
  <<: *airflow_report

kubernetes:
  <<: *airflow_report

ssh:
  <<: *airflow_report
