local:

docker:
  containers:
    - demo9b25c0_scheduler_1

kubernetes:
  - namespace: astronomer-amateur-cosmos-2865
    name: amateur-cosmos-2865-scheduler-bfcfbd7b5-vdvhn
    context: fritz@polaris.us-east-1.eksctl.io
    container: scheduler
