# Poetry pyproject.toml: https://python-poetry.org/docs/pyproject/
[build-system]
requires = ["poetry_core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

#[build-system]
#requires = ["setuptools>=42", "wheel", "nuitka"]
#build-backend = "nuitka.distutils.Build"

[tool.poetry]
name = "telescope"
version = "1.2.2"
description = "A tool to observe distant (or local!) Airflow installations, and gather metadata or other required data."
readme = "README.md"
authors = ["telescope <solutions@astronomer.io>"]
repository = "https://github.com/telescope/telescope"
homepage = "https://github.com/telescope/telescope"
include = ["telescope/config.yaml"]

[tool.poetry.scripts]
# Entry points for the package https://python-poetry.org/docs/pyproject/#scripts
"telescope" = "telescope.__main__:cli"

[tool.poetry.dependencies]
python = "^3.8"
importlib_metadata = { version = "^4.5.0", python = "<3.8" }
rich = "^11.1.0"
kubernetes = "^21.7"
fabric = "^2.6.0"
docker = "^5.0.3"
invoke = "^1.6.0"
PyYAML = "^6.0"
click = "^8.0.3"
tqdm = "^4.62.3"
xlsxwriter = "^3.0.2"
jmespath = "^0.10.0"
Jinja2 = ">2.10.1"
humanize = "^3.13.1"
lazyimport = "^0.0.4"

# Install these with poetry install -E charts
pandas = {version = "^1.3.4", optional = true}
plotly = {version = "^5.4.0", optional = true}
kaleido = {version = "^0.2.1", optional = true}

# Install these with poetry install -E upload
google-cloud-storage = {version = "^2.1.0", optional = true}
gcsfs = {version = "^2022.2.0", optional = true}
pyarrow = {version = "^7.0.0", optional = true}
fsspec = {version = "^2022.2.0", optional = true}

[tool.poetry.extras]
charts = ["pandas", "plotly", "kaleido"]
upload = ["google-cloud-storage", "gcsfs", "pyarrow", "fsspec", "pandas"]

[tool.poetry.dev-dependencies]
bandit = "^1.7.0"
black = {version = "^21.7b0", allow-prereleases = true}
darglint = "^1.8.0"
isort = {extras = ["colors"], version = "^5.9.3"}
mypy = "^0.910"
mypy-extensions = "^0.4.3"
pre-commit = "^2.14.0"
pydocstyle = "^6.1.1"
pylint = "^2.10.2"
pytest = "^6.2.4"
pyupgrade = "^2.24.0"
safety = "^1.10.3"
pytest-integration = "^0.2.2"
pytest-mock = "^3.6.1"
apache-airflow = "^2.2.1"
pytest-xdist = {extras = ["psutil"], version = "^2.4.0"}
nuitka = "^0.6.19.4"

[tool.black]
# https://github.com/psf/black
target-version = ["py38"]
line-length = 120
color = true

exclude = '''
/(
    \.git
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
    | env
    | venv
    | tests/
    | airflow_report/__main__.py
)/
'''

[tool.isort]
# https://github.com/timothycrosley/isort/
py_version = 38
line_length = 120

known_typing = ["typing", "types", "typing_extensions", "mypy", "mypy_extensions"]
sections = ["FUTURE", "TYPING", "STDLIB", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]
include_trailing_comma = true
profile = "black"
multi_line_output = 3
indent = 4
color_output = true

[tool.mypy]
# https://mypy.readthedocs.io/en/latest/config_file.html#using-a-pyproject-toml-file
python_version = 3.8
pretty = true
show_traceback = true
color_output = true

allow_redefinition = false
check_untyped_defs = true
disallow_any_generics = true
disallow_incomplete_defs = true
ignore_missing_imports = true
implicit_reexport = false
no_implicit_optional = true
show_column_numbers = true
show_error_codes = true
show_error_context = true
strict_equality = true
strict_optional = true
warn_no_return = true
warn_redundant_casts = true
warn_return_any = true
warn_unreachable = true
warn_unused_configs = true
warn_unused_ignores = true


[tool.pytest.ini_options]
# https://docs.pytest.org/en/6.2.x/customize.html#pyproject-toml
# Directories that are not visited by pytest collector:
norecursedirs =["tests/resources/", "hooks", "*.egg", ".eggs", "dist", "build", "docs", ".tox", ".git", "__pycache__", "telescope/reporters"]
doctest_optionflags = ["NUMBER", "NORMALIZE_WHITESPACE", "IGNORE_EXCEPTION_DETAIL"]

# Extra options:
addopts = [
  "--ignore=tests/resources/example-dag.py",
  "--strict-markers",
  "--tb=short",
  "--disable-warnings",
  "--numprocesses=auto",
  "--no-header",
  "--doctest-modules",
  "--doctest-continue-on-failure",
]
