name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [ '3.7', '3.8', '3.9' ]
        os: [ ubuntu-latest, macos-latest, windows-latest ]

    steps:
    - uses: actions/setup-python@v1
      with:
        python-version: '3.8'
        architecture: x64

    - uses: actions/checkout@v2

    - name: Install poetry
      run: make poetry-download

    - name: Set up cache
      uses: actions/cache@v2.1.6
      with:
        path: .venv
        key: venv-${{ matrix.python-version }}-${{ hashFiles('pyproject.toml') }}-${{ hashFiles('poetry.lock') }}

    - name: Build
      run: make package

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: telescope.pyz
        asset_name: telescope-${{ matrix.os }}-${{ matrix.python-version }}-amd64.pyz
        tag: ${{ github.ref }}
